### GET request to example server
POST http://localhost:3000/api/groups/66c9f1307cfaf063db4777e3/question
Content-Type: application/json
#Cookie: next-auth.session-token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..Q8mSAMPZ4Qo12TPR.AwFMPkY6eQAidK8fTpvFFDzy-pleu6GJlZZrx_NOkICIdBonuztUXfyEPmbwgFHBhp7eRLswgqGEuB6Yks7GTjmpwr1p5Aceqib6cSJiM5aCxKx-czy7ektXQMRUFdMY6E4d1USj3RL8218FssRkdharLtCGzCXII2m9ipNFISpGSXu4Y3gks__Rtgc44tOL3cg8HtZauJFlWCLx-oOEWoU1u6ETEaBa36pS_WwkttpBCHzquKVW4rBvzFnA30XokVQ-_rY9i9rNeyjMqtPdHqjRVkK8TUNez4kypPC0tSJCSKciobPbCpLnT5oMjEOLH_TmBh7u0KEQZzob1DCiM9QVnGyUXsq37LsLo7JM04PLLWTlP-_b8qIfveFPYYCTG4CmBenW4yutHrqAmvqtbgLLBxVVFyMHEyUQ2qouRQ.jgkMKCOlGNiDmnKHBCq13g

###